---
# SETUP TASKS

- name: "SETUP - Install lynis"
  apt:
    name: lynis
    state: present
    update_cache: yes

- name: "SETUP - Download Egida API Worker"
  get_url:
    url: https://github.com/antonioalfa22/egida-api-worker/releases/download/2.0.0/egida-api-worker
    dest: /usr/local/bin/egida-api-worker
    force_basic_auth: yes
    mode: "u=rwx,g=rwx,o=rwx"

- name: "SETUP - Create Egida API Worker service"
  template:
    src: services/egida-api-worker.service
    dest: /etc/systemd/system/egida-api-worker.service
    owner: root
    group: root
    mode: "u=rwx,g=rwx,o=rwx"

- name: "SETUP - Start Egida API Worker service"
  systemd:
    name: egida-api-worker
    daemon_reload: yes
    state: started