---
# SETUP TASKS

- name: "SETUP - Install lynis"
  apt:
    name: lynis
    state: present
  update_cache: yes
  tags:
      - lynis

- name: "SETUP - Download Egida API Worker"
  get_url:
    url: https://github.com/antonioalfa22/egida-api-worker/releases/download/2.0.0/egida-api-worker
    dest: /usr/local/bin/egida-api-worker
    force_basic_auth: yes
  tags:
      - egida-api-worker

- name: "SETUP - Create Egida API Worker service"
  template:
    src: services/egida-api-worker
    dest: /etc/init.d/egida-api-worker
    owner: root
    group: root
    mode: 0600

- name: "SETUP - Start Egida API Worker service"
  service:
    name: egida-api-worker
    state: started