#!/bin/bash
#
# chkconfig: 35 90 12
# description: Egida API Worker server
#

# Get function from functions library
. /etc/init.d/functions

# Start the service egida-api-worker
start() {
        initlog -c "echo -n Starting egida-api-worker server: "
        /usr/local/bin/egida-api-worker &
        ### Create the lock file ###
        touch /var/lock/subsys/egida-api-worker
        success $"egida-api-worker server startup"
        echo
}

# Restart the service egida-api-worker
stop() {
        initlog -c "echo -n Stopping egida-api-worker server: "
        killproc egida-api-worker
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/egida-api-worker
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status egida-api-worker
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0